// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYWaSyzk7wJBbMJkB4KVjd5yhlTMWluME',
    appId: '1:944897520122:web:6ce7948f6356001bebf443',
    messagingSenderId: '944897520122',
    projectId: 'payouts-5c75e',
    authDomain: 'payouts-5c75e.firebaseapp.com',
    storageBucket: 'payouts-5c75e.firebasestorage.app',
    measurementId: 'G-FW3KHL42ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7VtQxpL_DPASnQVOl-oJSWe_NVlgn5Z4',
    appId: '1:944897520122:android:85c4b005d842f190ebf443',
    messagingSenderId: '944897520122',
    projectId: 'payouts-5c75e',
    storageBucket: 'payouts-5c75e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtpRgQSQTVFgTnBMHP6OsQj9gKg24OG5s',
    appId: '1:944897520122:ios:db0dbbb9d02356ccebf443',
    messagingSenderId: '944897520122',
    projectId: 'payouts-5c75e',
    storageBucket: 'payouts-5c75e.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtpRgQSQTVFgTnBMHP6OsQj9gKg24OG5s',
    appId: '1:944897520122:ios:db0dbbb9d02356ccebf443',
    messagingSenderId: '944897520122',
    projectId: 'payouts-5c75e',
    storageBucket: 'payouts-5c75e.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYWaSyzk7wJBbMJkB4KVjd5yhlTMWluME',
    appId: '1:944897520122:web:7348b34ea44c57f7ebf443',
    messagingSenderId: '944897520122',
    projectId: 'payouts-5c75e',
    authDomain: 'payouts-5c75e.firebaseapp.com',
    storageBucket: 'payouts-5c75e.firebasestorage.app',
    measurementId: 'G-E3WKWQQ9LY',
  );
}
